#
# Workflow: Build PR
#

name: Build PR (Community, Branch)
on: pull_request

jobs:

  build-pr:

    name: "Build PR (Community, Branch) #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
    runs-on: ubuntu-latest

    steps:
    
      - name: Step
        shell: bash
        run: |
          echo "PR #${{ github.event.pull_request.number }}"
          if [ -z "${{ secrets.SOME_SECRET_TOKEN }}" ]; then
            echo "SECRET IS ABSENT"
          else
            echo "SECRET IS PRESENT"
          fi

  build-pr-call:
  
    name: "Call (Community, Branch)"        
    uses: ./.github/workflows/callme.yml
    secrets: inherit